### ISSUE TITLE
instances of `import benpy` - remove that!

### ISSUE THREAD

**Issue by brmather** [brmather/conduction#2]

**Comment by alex-dickinson** [comment]
Ok, thanks!

**Comment by brmather** [comment]
@alex-dickinson there are a number of examples that are deprecated which contain references to `benpy`. I'd recommend looking at the `invert_geological_model.py` script which I believe still works and demonstrates a progression from setting up the forward to inverting model of minimum misfit using the adjoint model.

**Comment by alex-dickinson** [comment]
Thanks Ben - I've tested the invert_geological_model.py script and it seems to be working. It didn't finish the inversion as I was just running it on my laptop - I'll try it on the university cluster when I get access and let you know.
